version:  "3"
services:

  db:
    image: mariadb:10
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    domainname: vcl.local
    hostname: db

  www:
    build: www
    env_file: .env
    volumes:
      - /var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: www

  managementnode:
    build: mgmt
    env_file: .env
    domainname: vcl.local
    hostname: mgmt
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - /var/log/vcl/

  ldap:
    image: osixia/openldap
    env_file: .env
    domainname: vcl.local
    hostname: ldap

  cas:
    image: apereo/cas:v5.2.2
    ports:
      - "8080:8080"
      - "8443:8443"
    domainname: vcl.local
    hostname: cas

volumes:
  mariadb_data:
