version:  "3"
services:

  db:
    image: mariadb:10
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    domainname: vcl.local
    hostname: db

  www:
    image: junaid/vcl-www:debug
    env_file: .env
    links:
      - db:db
    depends_on:
      - db
    domainname: vcl.local
    hostname: www
    ports:
      - "80:80"
      - "443:443"

  managementnode:
    image: junaid/vcl-mgmt
    env_file: .env
    domainname: vcl.local
    hostname: mgmt
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - /var/log/vcl/

  ldap:
    image: jtgasper3/openldap-basic
    domainname: vcl.local
    hostname: ldap
    ports:
      - "10389:389"

  cas:
    build: cas
    env_file: .env
    ports:
      - "8080:8080"
      - "8443:8443"
    domainname: vcl.local
    hostname: cas

volumes:
  mariadb_data:
